---
# Playbook to clone VM
# should be used with latest version of vsphere_guests.py
# After clone taks, let's modiy the VM

- name: deploy vm from clone
  hosts: localhost
  gather_facts: no
  tasks:
    - name: clone vm
      vsphere_guest:
        power_on_after_clone: False
        validate_certs: False
        vcenter_hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        guest: "{{ hostname }}"
        from_template: yes
        template_src: "{{ template }}"
        cluster: aci
        resource_pool: "/Resources/{{ pool }}"
        vm_extra_config:
          folder: Ansible

    - name: set specs
      vsphere_guest:
        state: reconfigured
        validate_certs: False
        vcenter_hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        guest: "{{ hostname }}"
        vm_hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ cpus }}"

    - name: power on VM
      vsphere_guest:
        state: powered_on
        validate_certs: False
        vcenter_hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        guest: "{{ hostname }}"

    - name: wait for the VM to boot
      pause: 
        prompt: "waiting for the VM to wake up"
        seconds: 30

    - name: gather some facts about this vm
      vsphere_guest:
        validate_certs: False
        vcenter_hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        guest: "{{ hostname }}"
        vmware_guest_facts: yes
