---
# Playbook to clone VM
# should be used with latest version of vsphere_guests.py
# After clone taks, let's modiy the VM

- name: remove VM
  hosts: localhost
  gather_facts: no
  tasks:
    - name: remove VM
      vsphere_guest:
        state: absent
        force: True
        validate_certs: False
        vcenter_hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        guest: "{{ hostname }}"
