---
# script to setup host 
# should be started via callback:
# curl -k --data "host_config_key=363efc3e7d85345c5a429d0d4ada4c23" https://tower01.t-i.demo:443/api/v1/job_templates/154/callback/

- name: setup host
  become: True
  gather_facts: True
  hosts: all
  tasks:
    - name: going to configure host
      debug: var=vmware_name

    - name: configure hostname
      hostname: name=vmware_name
