---
# script to setup host 
# should be started via callback

- name: setup host
  become: True
  gather_facts: True
  hosts: all
  tasks:
    - setup:
      register: out
  
    - debug: var=out
   
    - debug: var=vmware_guestState

    - dbueg: var=host
