---
# tasks to install docker on Ubuntu
#

- name: update package information
  apt: update_cache=yes

- name: install first serie of packages, should be installed for every Ubuntu version
  apt: name={{ item }} state=present
  with_items:
     - apt-transport-https
     - ca-certificates
     - linux-image-extra-{{ ansible_kernel }}

- name: install apparmor for 14.04 for 12.04
  apt: name=apparmor state=present
  when: ansible_distribution_version == "14.04" or "12.04"

- name: add apt key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: add apt source list
  copy:
    content: deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release}} main
    dest: /etc/apt/sources.list.d/docker.list
    force: yes

- name: again update package information
  apt: update_cache=yes

- name: remove lxc-docker if it exists
  apt: name=lxc-docker state=absent

- name: time to install docker
  apt: name=docker-engine state=present

